import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SEO from "@/components/SEO";

export default function CodeOfEthics() {
    return (
        <div className="min-h-screen bg-[#0F0F0E] flex flex-col font-serif">
            <SEO title="Code of Ethics | Bishouy.com" description="Our transparent commitments to the public." />
            <Navbar />
            <main className="flex-1 container pt-32 pb-24">
                <div className="max-w-3xl mx-auto">
                    <div className="mb-16">
                        <h1 className="font-display text-4xl md:text-5xl text-[#E8A020] mb-6">Code of Ethics</h1>
                        <p className="font-ui text-sm text-[#8A8880] tracking-widest uppercase mb-8">Our non-negotiable commitments to truth and transparency</p>
                    </div>

                    <div className="prose prose-invert max-w-none text-[#D4D0C8] space-y-8">
                        <section>
                            <h2 className="font-display text-2xl text-[#F2F0EB] border-b border-[#2A2A28] pb-2 mb-4">1. Verification and Fact-Checking</h2>
                            <p className="leading-relaxed">
                                Every factual claim passed through our system—whether generated by human reporters or assisted by AI analysis pipelines—must be verified against primary sources, official records, or empirical data. We do not publish hearsay as fact. Unverified reports are explicitly labeled as speculative or awaiting confirmation.
                            </p>
                        </section>

                        <section>
                            <h2 className="font-display text-2xl text-[#F2F0EB] border-b border-[#2A2A28] pb-2 mb-4">2. Artificial Intelligence Transparency</h2>
                            <p className="leading-relaxed">
                                We employ Large Language Models and AI systems for aggregation, summarization, and translation (e.g., our "Redazione AI" desk). Any material entirely generated or heavily structurally influenced by AI is clearly attributed to our AI desk. AI is a tool for scale, not a substitute for human editorial judgment.
                            </p>
                        </section>

                        <section>
                            <h2 className="font-display text-2xl text-[#F2F0EB] border-b border-[#2A2A28] pb-2 mb-4">3. Corrections and Accountability</h2>
                            <p className="leading-relaxed">
                                When we make an error, we correct it instantly, visibly, and without defense. We maintain a public log of substantive corrections attached to the original articles to preserve digital and historical integrity.
                            </p>
                        </section>

                        <section>
                            <h2 className="font-display text-2xl text-[#F2F0EB] border-b border-[#2A2A28] pb-2 mb-4">4. Sourcing and Anonymity</h2>
                            <p className="leading-relaxed">
                                We grant anonymity to sources only when their physical safety or livelihood is at imminent risk, and only when the information they provide is of critical public importance and unavailable elsewhere. Our editors know the identity of all anonymous sources.
                            </p>
                        </section>

                        <section>
                            <h2 className="font-display text-2xl text-[#F2F0EB] border-b border-[#2A2A28] pb-2 mb-4">5. Financial Independence</h2>
                            <p className="leading-relaxed">
                                Our reporters and editors are prohibited from accepting gifts, travel accommodations, or financial incentives from any subjects they cover. Editorial decisions are siloed completely from advertising and revenue departments.
                            </p>
                        </section>

                        <div className="mt-16 bg-[#1C1C1A] border-l-4 border-[#E8A020] p-6 text-sm">
                            <p className="font-ui uppercase tracking-widest text-[#8A8880] mb-2 font-bold">Document History</p>
                            <p className="text-[#555550]">Last revised: October 2024. This document is a living framework reviewed annually by the Executive Editor.</p>
                        </div>
                    </div>
                </div>
            </main>
            <Footer />
        </div>
    );
}
